server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  instance:
    hostname: localhost
    instance-id: order80
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #设置与eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/